/**
 * Writes src/sandbox/client-source.ts from src/sandbox/client.js, so the Worker can hand the
 * client's source to the sandbox isolate while node tests import client.js as a module.
 *
 *   node --experimental-strip-types scripts/build-sandbox.ts [--check]
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const from = new URL('../src/sandbox/client.js', import.meta.url);
const to = new URL('../src/sandbox/client-source.ts', import.meta.url);
const source = readFileSync(from, 'utf8');
const generated = `// Generated by scripts/build-sandbox.ts from src/sandbox/client.js. Do not edit; run pnpm sandbox:build.\nexport default ${JSON.stringify(source)};\n`;

if (process.argv.includes('--check')) {
  const current = existsSync(to) ? readFileSync(to, 'utf8') : '';
  if (current !== generated) {
    console.error('src/sandbox/client-source.ts is stale; run pnpm sandbox:build');
    process.exit(1);
  }
  console.log('src/sandbox/client-source.ts matches src/sandbox/client.js');
} else {
  writeFileSync(to, generated);
  console.log(`wrote src/sandbox/client-source.ts (${generated.length} chars)`);
}
